---
abstract: 'A Bundle Of Resources'
author:
  - 'Copyright (c) 2008 Daisuke Maki C<< daisuke@endeworks.jp >>'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.72'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Data-ResourceSet
no_index:
  directory:
    - inc
    - t
requires:
  Class::Accessor::Fast: 0
  Class::Data::ConfigHash: 0
  Class::Inspector: 0
  UNIVERSAL::require: 0
version: 0.00002
